[features]
seeds = false
[programs.localnet]
arcryptiannft_breeding_solana = "7MFw3o88qjGDRcvXr217A54cMp3chWi5qF2fng1qWshU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/chen34/.config/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
