[features]
seeds = false
[programs.localnet]
arcryptiannft_breeding_solana = "E27TrKv5EHKetcVKqRyvYiRUGdm7Ldxmp31h1c675SJP"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/chen34/.config/solana/devnet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
